name: 'Hub and Spoke'

on:
  workflow_dispatch:
    inputs:
      jobToRun:
        description: 'Select Job'
        required: true
        default: 'DeployHubSpoke'
        type: choice
        options:
          - DeployHubSpoke
          - DestroyHubSpoke

env:
  terraformVersion: '1.12.2'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-HubSpoke:
    if: ${{ github.event.inputs.jobToRun == 'DeployHubSpoke' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Terraform Init
        run: |
          cd modules/hub-spoke
          terraform init 

      - name: Terraform Plan
        run: |
          cd modules/management-groups
          terraform plan -out=tfplan
        
      - name: Terraform Apply
        if: ${{ success() }}
        run: |
          cd modules/hub-spoke
          terraform apply -auto-approve

  destroy-hubspoke:
      if: ${{ github.event.inputs.jobToRun == 'DestroyHubSpoke' }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd modules/hub-spoke
          terraform init
        
      - name: Terraform Destroy
        run: |
          cd modules/hub-spoke
          terraform destroy -auto-approve
